# Generated by Django 4.0.1 on 2022-05-26 10:46

import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('religion', models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('phone_number', models.CharField(max_length=23)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('personality', models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=250)),
                ('age_range', models.CharField(max_length=250)),
                ('roomie_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('roomie_religion', models.CharField(choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('roomie_personality', models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("I_DON'T_MIND", 'Others')], max_length=250)),
                ('roomie_age', models.CharField(max_length=200)),
                ('roomate_description', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('street_address', models.CharField(max_length=250)),
                ('room_type', models.CharField(max_length=250)),
                ('no_of_persons', models.IntegerField()),
                ('no_of_current_roomies', models.IntegerField()),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=12)),
                ('date_to_move', models.DateField(default=django.utils.timezone.now)),
                ('rent_per_person', models.DecimalField(decimal_places=2, max_digits=100)),
                ('additional_cost', models.CharField(max_length=250)),
                ('listing_title', models.CharField(max_length=250)),
                ('additional_information', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('is_active', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomate_request', to='core.profile')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.roomaterequest')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100)),
                ('roomate_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
