# Generated by Django 4.0.1 on 2022-04-16 09:27

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('religion', models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity')], max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=250)),
                ('phone_number', models.IntegerField(null=True)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('personality', models.CharField(choices=[('INTROVERT ', 'Introvert'), ('EXTROVERT', 'Extrovert')], max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('roomate_description', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
