# Generated by Django 4.0.1 on 2022-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert')], max_length=250),
        ),
    ]
