# Generated by Django 4.0.1 on 2022-05-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='roomate_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.roomaterequest'),
        ),
    ]
