# Generated by Django 4.0.1 on 2022-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roomie_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roomie_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roomie_personality',
            field=models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("DON'T MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roomie_religion',
            field=models.CharField(choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("DON'T MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("DON'T MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("DON'T MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roomate_description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
