# Generated by Django 4.0.1 on 2022-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_age_profile_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomaterequest',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='roomaterequest',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roomie_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roomie_personality',
            field=models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roomie_religion',
            field=models.CharField(choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ("I_DON'T_MIND", 'Others')], max_length=250, null=True),
        ),
    ]
