# Generated by Django 4.0.1 on 2022-05-30 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_connection_roomate_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='roomate_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.roomaterequest'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
