# Generated by Django 4.0.1 on 2022-05-11 12:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roomaterequest_latitude_roomaterequest_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
