# Generated by Django 4.0.1 on 2022-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_connection_user_connection_reciever_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
