# Generated by Django 4.0.1 on 2022-06-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
