# Generated by Django 4.0.1 on 2022-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
