# Generated by Django 4.0.1 on 2022-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0004_alter_customuser_is_active_alter_waitlist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
