# Generated by Django 4.0.1 on 2022-04-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0005_alter_waitlist_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
